# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IU CTF Tools
email: iuctf-l@indiana.edu
description: > # this means to ignore newlines until "baseurl:"
  We write/keep awesome instructions for the tools that IU CTF works on.
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://iuctf.github.io" # change this to the base hostname & protocol for your site
twitter_username: iuctf
github_username:  iuctf

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build 
exclude: [vendor, "Gemfile", "Gemfile.lock"]

theme: jekyll-theme-slate